// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVE0mI0D-ak9TTIUte7gO0lArcBi8Ew10',
    appId: '1:118120801173:web:e4ba5681afc1f13e740c9c',
    messagingSenderId: '118120801173',
    projectId: 'playfirebase-9a06d',
    authDomain: 'playfirebase-9a06d.firebaseapp.com',
    storageBucket: 'playfirebase-9a06d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgMTslQbPsqvQnUU-4bAgZuL7OXCh8lcs',
    appId: '1:118120801173:android:7d62123ba4e6dafd740c9c',
    messagingSenderId: '118120801173',
    projectId: 'playfirebase-9a06d',
    storageBucket: 'playfirebase-9a06d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA18RUMIKZT_a4q6wXMmX4vhFu03B-xWhQ',
    appId: '1:118120801173:ios:467b0df828a7460a740c9c',
    messagingSenderId: '118120801173',
    projectId: 'playfirebase-9a06d',
    storageBucket: 'playfirebase-9a06d.appspot.com',
    iosClientId:
        '118120801173-m9vdde6ntf6a93k50cc97fu9mgqcvtpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tryFirbs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA18RUMIKZT_a4q6wXMmX4vhFu03B-xWhQ',
    appId: '1:118120801173:ios:467b0df828a7460a740c9c',
    messagingSenderId: '118120801173',
    projectId: 'playfirebase-9a06d',
    storageBucket: 'playfirebase-9a06d.appspot.com',
    iosClientId:
        '118120801173-m9vdde6ntf6a93k50cc97fu9mgqcvtpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tryFirbs',
  );
}
